### ISSUE TITLE
Big Stone Gap WTP

### ISSUE THREAD

**Issue by jdkleiner** [HARPgroup/vahydro#186]
Elements
- River segment model: om-model-info/5831933
- Facility model: om-model-info/4826467

Additional Info
- Please provide the elevation of each release gate, and the operational status of each gate as well. Please explain how the gates are controlled (manually/remotely, etc.). Also, please confirm that there are no other release structures such as low flow valves.
  - Response:  The Dam contains three (3) 16” x 16” control gates and one (1) 36” x 36” control gate.  The elevations of these gates are shown on the attached record drawing sheet.  Each gate is controlled hydraulically, either manually or remotely.  The system is connected to the Town’s telemetry system and controlled primary from the water treatment plant so that the operators can monitor the amount of water discharged and bypassed.  There are no other structures that control the release of water.  The emergency spillway elevation is located at an elevation of approximately 1320 ft.
- Please provide a table showing the stage-storage relationship for Big Cherry Reservoir, including at least the total useable storage at each release gate level, but preferably at set intervals between the maximum pool and the lowest useable pool level.
  - Response:  Find attached the stage vs. storage table with the requested information.  The emergency spillway elevation is 1320 ft and full pool.
- Please provide the useable volume of Big Cherry Reservoir (I already have the full volume, but this additional information will be useful). In other words, how much of the reservoir is not able to be released by the gates or any other device.
  - Response:  The entire volume of the reservoir can be used.  The bottom 36” x 36” control gate invert elevation is located at the approximate stream bottom elevation. 
  - [Stage vs Storage.PDF](https://github.com/HARPgroup/vahydro/files/4765179/Stage.vs.Storage.PDF)
  - [Big Cherry Outlet Works Record Drawings.pdf](https://github.com/HARPgroup/vahydro/files/4765181/Big.Cherry.Outlet.Works.Record.Drawings.pdf)

#### BIG STONE GAP WTP: 
| hydroid  | substring                      | model_rseg    | model_pid  | available_mgd               | OM element | imp_off | Facility Name     | Intake Name             | Intake Total 2019 MGY |
|----------|--------------------------------|---------------|------------|-----------------------------|------------|---------|-------------------|-------------------------|-----------------------|
| 72672    | BIG STONE GAP WTP:Powell River | TU3_8880_9230 | 4826467    |  (Qintake - flowby) / 1.547 | 247367     | 1       | BIG STONE GAP WTP | SOUTH FORK POWELL RIVER | 830.298               |

##### Notes: 
- Add the flowby of 0.5 into the existing intake for that user, and then run some alternate scenarios with the 10% flowby,  I would recommend doing only 2000-2002 so these will run very swiftly. Use runid 201 to experiment.
- If we know the impoundments release rules, we need to add the impoundment as a "Local Tributary" and then simulate its releases.
  - See: [Adding a New Watershed or Sub-watershed](https://github.com/HARPgroup/vahydro/wiki/Adding-a-New-Watershed-or-Sub-Watershed)
![BigStoneGapWTP](https://user-images.githubusercontent.com/29379385/78560875-c20b7100-77e4-11ea-9a3e-e7cbb9bedf33.png)

## Cassie: 
"This is an existing water intake constructed in the 1960's with an upgrade in the early 1980's. The Town owns and operates the Big Cherry Dam located approximately 3 miles upstream from the intake structure. The Town's water treatment plant operators control the amount of water discharging the dam into the Powell River and all of the stream by-pass flow to meet the previous permit requirements of 4.0 MOD of maximum withdrawal and 0.50 MGD of by-pass flow. This is always true unless the dam is overflowing exceeding the amount of water required from various rainfall events. Therefore, the existing/proposed maximum withdrawal amounts will not have an impact on the stream in terms of rates, volumes, frequency, etc. This is a daily activity as it serves the existing water treatment plant."

**Comment by rburghol** [comment]
[01-0688_PermitBigStoneGap_2003-08-25.pdf](https://github.com/HARPgroup/vahydro/files/4746194/01-0688_PermitBigStoneGap_2003-08-25.pdf)

**Comment by jdkleiner** [comment]
## Subwatershed is not yet in VAHydro, use NHD to create a shape for import.
```php get_nhd_basins.php "Lake Pelham - Mountain Run" 36.846465 -82.672071```

**Comment by jdkleiner** [comment]
Issue migrated to GitLab
