### ISSUE TITLE
Facility Model to WSP System Linkage

### ISSUE THREAD

**Issue by jmineva** [HARPgroup/vahydro#23]
Prerequisites: 
1. ~~Every facility needs at least one VAHydro 1.0 model element (one per river segment)~~ #24 
2. ~~Each WSP system is linked to facility using remote linkage (dh_link_feature_submittal)~~
3. ~~We need a method to easily handle when we change the link from a WSP System to its Facility (like with the major GW users that had the wrong linkage 12/31/2019 attn: @jdkleiner )~~
    1. ~~Remove an obsolete WSP2020... property from a facility that no longer has a WSP link.~~
    2. ~~Create wsp2020... for facilities that NEWLY have WSP link~~

## Updated workflow below: 
1. Use SQL to both sum and partition Facility WSP demand values handling both cases where there are 1:Many Facility:System, and 1:Many System:Facility. See: https://github.com/HARPgroup/vahydro/wiki/Partitioning-Demands-for-WSP-Systems-to-Facilities
1. ~~View sums wsp current (2020) and future (2040) values for all facilities linked to one or more system `/facility-system-withdrawal-sum`~~
    - This view needs to be updated to multiply the wsp_current_pw_fraction and wsp_future_pw_fraction 
  - Resolve issue #73 
Current: 

| featureid | entity_type | varkey | propvalue | propname | propcode |
| --- | --- | --- | --- | --- | --- |
| 66848 | dh_feature | wsp_facility_mgy | 6.169 | wsp2020_2020_mgy | wsp_current_use_mgy |

Future: 

| featureid | entity_type | varkey | propvalue | propname | propcode |
| --- | --- | --- | --- | --- | --- |
| 66848 | dh_feature | wsp_facility_mgy | 85.933 | wsp2020_2040_mgy | wsp_wd_future_mgy |

2. Use feeds importer to set a 2020 and a 2040 property on every facility with a system link
    - Importer: `import/import_facility_wsp_properties`
    - Perform 2 imports using the 2 exports from the view above:
        - `/facility-system-withdrawal-sum-current-export`
        - `/facility-system-withdrawal-sum-future-export`
3. Map `om_class_AlphanumericConstant` properties to facility:riverseg model props `wsp2020_2020_mgy` and `wsp2020_2040_mgy`

#### Alternative Links wsp2020_2020_mgy and wsp2020_2040_mgy
- Altered to use propname instead of varkey as filter for which properties to link
- Used dh_feature as source property, since the property is a standard propvalue type attached to the facility, and the linking framework expects that as default.
    - This prevents deleted and replaced facility properties from breaking the link to the model
- Batch file syntax:
  - ```drush scr modules/om/src/om.model.wsp.props.php file ../files/vahydro/fac_model_wsp_props-v02-short.txt```
```
copy (  
  SELECT model.pid AS dest_id,
    facility.hydroid AS src_id,
    'om_class_Equation' AS prop_varkey,
    wsp_prop.propname AS src_prop,
    wsp_prop.propname AS dest_prop,
    'dh_feature' AS src_entity_type
  FROM dh_feature AS facility
  INNER JOIN dh_properties AS model
    ON (
      model.featureid = facility.hydroid  
      AND model.propcode = 'vahydro-1.0'
    )
  INNER JOIN dh_properties AS wsp_prop 
    ON (
      wsp_prop.featureid = facility.hydroid  
-- only get specific vars now
      AND wsp_prop.propname in ('wsp2020_2020_mgy', 'wsp2020_2040_mgy')
    )
  WHERE facility.bundle = 'facility' 
   --INNER JOIN to only return facilities with models for version 1.0
  and model.pid is not null
  --INNER JOIN to only return facilities with wsp_facility_mgy properties
  and wsp_prop.pid is not null
  ORDER BY wsp_prop.featureid DESC
) to '/tmp/fac_model_wsp_props-v02.txt' WITH HEADER CSV DELIMITER E'\t';

```

**Comment by jdkleiner** [comment]
`SELECT facility_model.hydroid AS facility_hydroid, 
	system.adminid AS system_adminid,
	facility_model.pid AS model_pid,
	facility_model.propname AS model_propname,
	system.name AS system_name,
	system.admincode AS system_admincode,
	'om_class_Equation' AS varkey,
	'wsp2020_2020_mgy' AS propname
FROM (
  select name, admincode, adminid, ftype, dh_link_feature_submittal_target_id, dh_adminreg_feature.bundle 
  from dh_adminreg_feature 
  LEFT OUTER JOIN field_data_dh_link_feature_submittal AS entity_ref 
	ON adminid = entity_ref.entity_id 
  WHERE dh_adminreg_feature.bundle = 'submittal' AND
	dh_adminreg_feature.ftype LIKE 'wsp_plan_system%'
) AS system
FULL JOIN (
  select facility.hydroid, model.pid, model.propname
  FROM dh_feature AS facility 
  LEFT OUTER JOIN dh_properties as model
	ON (
		model.featureid = facility.hydroid  
		AND model.varid IN (SELECT hydroid FROM dh_variabledefinition WHERE varkey = 'om_water_system_element')
	) 
  where pid is not null
) as facility_model 
ON (facility_model.hydroid = system.dh_link_feature_submittal_target_id)
WHERE (1 = 1) 
GROUP BY facility_model.hydroid, system.adminid, facility_model.pid, facility_model.propname, system.name, system.admincode;`

**Comment by jdkleiner** [comment]
```
--- VAHydro riverseg:facility Missing match in OM 
copy (
  select a.wd_elementid, a.wd_name, a.vadeq_userid as om_userid, b.hydroid, b.vadeq_userid  as 
  vahydro_userid
  from tmp_rseg_withdrawals as a 
  FULL join tmp_vahydro_models as b
  on (a.vadeq_userid = b.vadeq_userid )
  where a.wd_elementid IS NOT null
  AND b.hydroid IS null
) to '/tmp/om_wds-missing-vahydro.txt' WITH CSV HEADER  delimiter E'\t';
```

**Comment by jdkleiner** [comment]
### **_Follow The Process Below_** (to set historic_monthly_pct property on facility models)

```
# Test setting one
cd /var/www/html/d.dh
  drush scr modules/om/src/om.model.wsp.props.php cmd 4730613 4748743 "om_class_DataMatrix" "historic_monthly_pct" "field_dh_matrix" "dh_properties"
```

```
psql -h dbase2 drupal.alpha
```

```
copy ( 
  SELECT model.pid AS dest_id,
    monfacs.pid AS src_id,
    'om_class_DataMatrix' AS prop_varkey,
    'historic_monthly_pct' AS dest_prop,
    'field_dh_matrix'AS src_prop,
    'dh_properties' AS src_entity_type
  FROM dh_feature AS facility
  INNER JOIN dh_properties AS model --INNER JOIN to only return facilities with models
    ON (
      model.featureid = facility.hydroid  
      AND model.varid IN (SELECT hydroid FROM dh_variabledefinition WHERE varkey = 'om_water_system_element')
    )
  INNER JOIN dh_properties AS monfacs --INNER JOIN to only return facilities with wd_current_mon_factors properties
    ON (
      monfacs.featureid = facility.hydroid  
      AND monfacs.varid IN (SELECT hydroid FROM dh_variabledefinition WHERE varkey = 'wd_current_mon_factors')
    )
  WHERE facility.bundle = 'facility'
  ORDER BY monfacs.featureid DESC
) to '/tmp/fac_model_historic_monthly_pct.txt' WITH HEADER CSV DELIMITER E'\t';
```

```
Ctrl+Z
cd /var/www/html/files/vahydro
sftp dbase2 
get /tmp/fac_model_historic_monthly_pct.txt
bye

# Create a test set
head -n 6 fac_model_historic_monthly_pct.txt > fac_model_historic_monthly_pct_head5.txt

cd /var/www/html/d.alpha
drush scr modules/om/src/om.model.historic_monthly_pct.php file ../files/vahydro/fac_model_historic_monthly_pct_head5.txt

# Set all
drush scr modules/om/src/om.model.historic_monthly_pct.php file ../files/vahydro/fac_model_historic_monthly_pct.txt
```
