### ISSUE TITLE
Local and Cumulative Drainage Areas for P6-Updated River Segments

### ISSUE THREAD

**Issue by hdaniel7** [HARPgroup/vahydro#40]
The geometries of a few river segments were updated between P5 and P6 (and some new segments were added)! Each of these river segments has drainage area properties that we uploaded to the river segment feature (example: "wshed_local_area_sqmi" and "wshed_drainage_area_sqmi" attached to the river segment feature [here](http://deq2.bse.vt.edu/d.dh/admin/content/dh_features/manage/67816/dh_properties)).  Each of these river segments also has a local and cumulative drainage area attached to their "0. River Channel" element within the Modeling subsection (example: "area" and "drainage area" attached to the "0. River Channel" element within the model with code "vahydro-1.0", shown [here](http://deq2.bse.vt.edu/d.dh/om-model-info/4784962)).  We need to ensure that these areas are identical between these two locations for any segment with updated geometry, as well as for any segment immediately upstream/downstream of a segment with updated geometry.  I'll post a list here of segments which need checking in the coming days -- they'll just be the segments mentioned in [this issue](https://github.com/HARPgroup/cbp6/issues/100).

Segments to investigate:
PU1_4840_4760
PU2_4720_4750
PU1_4760_4451
PU2_4750_4451
PU3_4451_4450
PU3_4450_4440
PU4_4440_3970
PM1_3711_3710
PM1_3710_4040
PM4_4040_4410
PM1_4251_4250
PM1_4252_4250
PM1_4250_4500
PM1_4500_4580

**Comment by kevindandrea** [comment]
I went ahead into GIS and looked into the River Segments in question above. This excel [document](https://drive.google.com/open?id=1p5x34ywr3pLIZ-qooLpHOeag6clMRfAQ), which can be found in Analysis folder in the cbp6 google drive folder, highlights my findings. I will go ahead now into VAHydro and being comparing the areas that I have calculated to what is listed in VAHydro.

**Comment by kevindandrea** [comment]
I have just gone into VAHydro and manually made the following changes to the local drainage areas associated with the VAHydro-1.0 model under the River Channel Properties:

1. River Segment: PM1_3711_3710 - Lingamore Creek
-Previous Local Drainage Area - 89.0468050137963 square miles 
-New Local Drainage Area - 81.07866046 square miles 

2. River Segment: PM1_3710_4040 - Lingamore Creek
-Previous Local Drainage Area - 89.0468050137963 square miles 
-New Local Drainage Area - 7.968144448 square miles 

3. River Segment: PM1_4251_4250 - Little Seneca Creek Lake
-Previous Local Drainage Area -  101.831862375187 square miles 
-New Local Drainage Area -  21.18668944 square miles 

4. River Segment: PM1_4252_4250 - Long Draught Branch at Clopper Lake
-Previous Local Drainage Area -  101.831862375187 square miles 
-New Local Drainage Area -  2.926165631 square miles 

5. River Segment: PM1_4250_4500 - Great Seneca Creek
-Previous Local Drainage Area - 101.831862375187 square miles 
-New Local Drainage Area -  77.71900718 square miles

If there are any issues with the changes I have made, or my methodology, please let me know and we can discuss and alleviate said issues. It is definitely worth checking into the cumulative drainage areas of these segments, which is something I plan on looking into later this week.

**Comment by kevindandrea** [comment]
I have just gone into VAHydro and manually made the following changes to the cumulative drainage areas associated with the VAHydro-1.0 model under the River Channel Properties:

1. River Segment: PM1_3711_3710 - Lingamore Creek
-Previous Cumulative Drainage Area - 89.04646145 square miles
-New Cumulative Drainage Area - 81.07866046 square miles

2. River Segment: PM1_4251_4250 - Little Seneca Creek Lake
-Previous Cumulative Drainage Area - 101.831862375187 square miles
-New Cumulative Drainage Area - 21.18668944 square miles

3. River Segment: PM1_4252_4250 - Long Draught Branch at Clopper Lake
-Previous Cumulative Drainage Area - 101.831862375187 square miles
-New Cumulative Drainage Area - 2.926165631 square miles

4. River Segment: PM1_4250_4500 - Great Seneca Creek
-Previous Cumulative Drainage Area - 50.1 square miles
-New Cumulative Drainage Area - 101.8314695 square miles

If there are any issues with the changes I have made, or my methodology, please let me know and we can discuss and alleviate said issues. Some of these changes are pretty significant, so I will make sure the models for these river segments get re-run prior to running the model for the entire river basin that they are contained in.

**Comment by hdaniel7** [comment]
Your process looks right to me! Thanks for knocking out this analysis, Kevin!

**Comment by rburghol** [comment]
Awesome -- thanks!
