### ISSUE TITLE
Rapidan River: Improperly Modeled Flows Starting Jan. 2006

### ISSUE THREAD

**Issue by hdaniel7** [HARPgroup/vahydro#41]
For river segment [RU5_6030_0001](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/67775) [Rappahannock River @ Fall Line], flows seem to be modeled incorrectly beginning in Jan. 2006.  Since this issue begins in Jan. 2006, immediately after the 31 Dec. 2005 end date of the phase 5 model, it is thought that the issue might be linked with the new, phase 6 inputs?

This issue can be seen starting in 2006 in the hydrographs of the following image:
![image](https://user-images.githubusercontent.com/4571170/67941318-c2576e80-fbab-11e9-8fa1-4c8340f84e9a.png)

After re-running the main stem of the Rapidan, I still noticed elevated flows... then realized I *also* needed to rerun the Robinson River (a trib to the Rapidan).  In the process of figuring this out I created two quick scripts that take only a simple box-whisker of flow (from a watershed element) and unit area runoff (from the 1. Local... element).  These are very effective plots because they rapidly inform us that something cruddy is happening:

Example: Flow in Robinson river segment RU2_5940_6200 (see example script [flows.R](https://github.com/HARPgroup/vahydro/blob/master/R/examples/flows.R) )
![image](https://user-images.githubusercontent.com/4571170/68047968-f028da00-fcb5-11e9-95b7-50baf0672cf3.png)

Runoff in that same segment (see example script [runoff.R](https://github.com/HARPgroup/vahydro/blob/master/R/examples/runoff.R) )
![image](https://user-images.githubusercontent.com/4571170/68048072-29614a00-fcb6-11e9-8f42-4c4c02ada0df.png)

Flow in Rapidan, upstream of confluence with Robinson (this is expected time series behavior)
![image](https://user-images.githubusercontent.com/4571170/68048187-72b19980-fcb6-11e9-81c9-20fa214268c8.png)

Full dashboard file: [Rappahannock River near Fredericksburg_Working_Gage_Vs_Vahydro_Dashboard_2019.pdf](https://github.com/HARPgroup/cbp6/files/3780107/Rappahannock.River.near.Fredericksburg_Working_Gage_Vs_Vahydro_Dashboard_2019.pdf)

**Comment by rburghol** [comment]
I am pretty sure we need to look at the upstream Tributaries for this.  The anomalous flows from 2006 onward do not seem to be originating in either the local Runoffs, reservoirs, or the local channel.

**Comment by rburghol** [comment]
Specifically - at a glance, the flows from the Rapidan look too large, whereas upstream flows from the Rappahannock look OK to me.

**Comment by rburghol** [comment]
I propose that we produce, as a matter of course for each and every model segment (part of our dashboards eventually), the Runit at each segment, by year.  Perhaps the most effective would be a box and whisker of the Runit at the segment (from 1. Local...) grouped by year, which would allow us to spot a segment that didn't look quite right.  For these, we would be looking for something where the lower part of the box and/or whisker seemed too high.

**Comment by rburghol** [comment]
And here we go.  Rapidan tributaries (at least one of them that is), did not get their Runit lookup data matrix set appropriately.  They still used the Phase 5.3.2 runoff for all flow_modes greater than 3, and there fore they had a constant Runit coming in after 2005. Apparently, the last day of the 2005 simulation in Rapidan was a rainfall event so... lotsa water.

```

year | Runit_mean | Runit_quantile | Qvahydro_unit_mean | Qcbp6_unit_mean
-- | -- | -- | -- | --
1984 | 0.805003711080217 | 0.181 | 0.805003711080217 | 0.765906085773649
1985 | 0.789221821766006 | 0.105 | 0.789221821766006 | 0.77913521884484
1986 | 0.431199586436082 | 0.055 | 0.431199586436082 | 0.485278379759233
1987 | 1.02887550514219 | 0.057 | 1.02887550514219 | 0.981302306485958
1988 | 0.49947161478034 | 0.070 | 0.49947161478034 | 0.579423007125358
1989 | 0.944082986647669 | 0.276 | 0.944082986647669 | 0.961928935074317
1990 | 0.875488462764369 | 0.142 | 0.875488462764369 | 0.879604432372543
1991 | 0.537642477297643 | 0.057 | 0.537642477297643 | 0.580887002352881
1992 | 0.654016301539921 | 0.146 | 0.654016301539921 | 0.777761249500261
1993 | 1.37327614297489 | 0.071 | 1.37327614297489 | 1.39910385263244
1994 | 1.35093773021289 | 0.165 | 1.35093773021289 | 1.29674350395563
1995 | 0.863968794515974 | 0.161 | 0.863968794515974 | 0.780584276862232
1996 | 1.87490844905448 | 0.528 | 1.87490844905448 | 1.42494176290084
1997 | 0.982241083192489 | 0.171 | 0.982241083192489 | 0.759151143890486
1998 | 1.39913413191991 | 0.028 | 1.39913413191991 | 1.52093499775768
1999 | 0.476456802005343 | 0.033 | 0.476456802005343 | 0.630239044533863
2000 | 0.447322562603664 | 0.096 | 0.447322562603664 | 0.608592619166395
2001 | 0.435324076070142 | 0.020 | 0.435324076070142 | 0.539867864475743
2002 | 0.25581319902993 | 0.028 | 0.25581319902993 | 0.456767288778076
2003 | 2.10875321393485 | 0.578 | 2.10875321393485 | 2.16858750895163
2004 | 0.868808629191297 | 0.301 | 0.868808629191297 | 0.91935736637528
2005 | 0.764670805139762 | 0.085 | 0.764670805139762 | 0.945339110574716
2006 | 1.26407119799511 | 1.264 | 1.26407119799511 | 0.735109752415751
2007 | 1.26407119799511 | 1.264 | 1.26407119799511 | 0.575488239970584
2008 | 1.26407119799511 | 1.264 | 1.26407119799511 | 0.655155347903827
2009 | 1.26407119799511 | 1.264 | 1.26407119799511 | 0.851159977588572
2010 | 1.26407119799511 | 1.264 | 1.26407119799511 | 0.941424686061659
2011 | 1.26407119799511 | 1.264 | 1.26407119799511 | 1.00576188544764
2012 | 1.26407119799511 | 1.264 | 1.26407119799511 | 0.485002905758497
2013 | 1.26407119799511 | 1.264 | 1.26407119799511 | 0.927234906338905
2014 | 1.26407119799511 | 1.264 | 1.26407119799511 | 1.05907488191043
```

**Comment by rburghol** [comment]
I updated the erroneous Runit lookups in the Rapidan River -- all other Rappahannock tribs seemed good to go, though we should subject everything to the runoff anakysis as part of our model QA routines as discussed.  I triggered a re-run and run 120 completed yesterday.  I kicked off run 121 this morning.  FWIW, by using a cache date of 10/1/2019, only the minimum necessary components ran, which is nice.  

Regarding the cache date. I checked each of the "1. Local..." elements as per the previous comments tabular output, and all had CBP6_unit values that varied during the 2006-2014 time period, suggesting that there was no problem with those time series source files, nor with their execution.  Since this was an error in the "1. Local Runoff..." component, there was no need to re-run the individual land-river segments, resulting in a considerable time savings in execution.

If you could regenerate the dashboard files for run 121, or simply print out the R commands that you use to do so here in this issue, I will be glad to regenerate them myself (it would be good for me to learn).  Will keep you posted regarding run 121!

**Comment by hdaniel7** [comment]
Per our discussion this morning (and as shown in this gage vs. base hydrograph):
![fig1](https://user-images.githubusercontent.com/36606075/68160402-c247cd80-ff21-11e9-85a9-095fb346dc1c.png)
the issue seems to have been resolved -- I'm closing out this issue until any other concerns arise about this segment (and I'm working on implementing the Runit boxplots for QA at the moment!)
