### ISSUE TITLE
Jennings Randolph: Flows appear overly riverine and relatively unaffected by impoundment

### ISSUE THREAD

**Issue by hdaniel7** [HARPgroup/vahydro#42]
The following dashboards were generated using phase 6 base vs. climate change data and phase 6 base vs. gage flow data for segment [PU3_4450_4440](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/67816) [North Branch Potomac below Bloomington/Jennings Randolph] -- Rob noted that the flows appeared more riverine and less affected by the impoundment than would be expected -- it was noted that perhaps the local drainage area of the segment was incorrect.

[JenningsRandolph_base_vs_cc.pdf](https://github.com/HARPgroup/cbp6/files/3780134/JenningsRandolph_base_vs_cc.pdf)
[JenningsRandolph_gage_vs_base.pdf](https://github.com/HARPgroup/cbp6/files/3780154/JenningsRandolph_gage_vs_base.pdf)

I checked into it and realized that the total drainage area of the segment immediately upstream ([PU3_4451_4450](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/454132) [Bloomington/Jennings Randolph]) was incorrect -- I fixed this and began re-running the model.  I'll post the updated results here when the run is completed, but I'm not sure how much of a difference in the flow magnitudes this will make.

**Comment by hdaniel7** [comment]
First off, for the VA Hydro 120 (base) vs VA Hydro 121 (CC) runs: flows were quite similar, as shown in this hydrograph: 
![fig1](https://user-images.githubusercontent.com/36606075/68166885-c54aba00-ff31-11e9-9454-d62becfcecb1.png)
The metrics in the table confirmed this closeness, with an overall mean flow difference of +3.25% and the vast majority of the other metrics having a percent difference of -2 to +10%.

Next up, for VA Hydro 120 vs. gage: overall mean flow was quite accurately measured (percent difference of +4.64%) but the vast majority of other metrics were quite inaccurate, with few of the metrics having percent differences smaller in magnitude than +/-10% -- I believe this is due to the increased challenge in modeling the impoundment over an impoundment-less segment and does not signify a problem to be fixed, just a place for possible improvement in the future.  You can see in the zoomed hydrograph here:
![fig2](https://user-images.githubusercontent.com/36606075/68167280-f7105080-ff32-11e9-9a31-e6adf79845b2.png)
that the impoundment is certainly being modeled and having an effect on modeled flow (due to the horizontal lines of considerable length showing times of regulated outlet flows from the impoundment).  

Also of note is the flow exceedance graph, shown here:
![fig3](https://user-images.githubusercontent.com/36606075/68167392-4bb3cb80-ff33-11e9-8361-5fb28c6981cb.png)
I'd say that the VA Hydro model now appears to have 3 distinct "steps" showing common flows exiting the impoundment -- one at about 600 cfs from about 55% to 70%, one at about 200 cfs from about 85-90%, and one at about 150 cfs at about 92-95%.  One area where the VA Hydro model seems to fall a bit short is in modeling the flows of the smallest magnitude -- while the smallest flows commonly seen at the gage are about 95 cfs, there seems to be 3-4% of modeled flows falling below this 95 cfs baseline, dropping down to about 10 cfs -- possibly something to look into in the future to improve the modeling of this impoundment.

**Comment by rburghol** [comment]
Thanks Daniel, and I agree that :
1. We have sorted out the drainage area issues.
2. The last figure indicates improved but not yet good enough reservoir ops.

I would like to take this one on as a particular case study to work with our colleagues at ICPRB to see how we can improve this performance (within reason of course).

**Comment by hdaniel7** [comment]
Sounds great! Let me know if there's anything I can do to help with that.
