### ISSUE TITLE
Appomattox 0001: Incredibly small, cyclical flows for entire study period

### ISSUE THREAD

**Issue by hdaniel7** [HARPgroup/vahydro#43]
For the river segment [JA5_7480_0001](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/68373) [George F. Brasfield Dam], flows are identical between the base and climate change scenarios.  The maximum metrics peak at under 10cfs, while minimum metrics are all above 4cfs.  Flows all appear to be perfectly cyclical. The two segments upstream, [JA2_7570_7480](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/68323) [West Creek (Deep Creek, Appomattox)] and [JA4_7470_7480](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/67969) [Appomattox River] have both been run and appear to have reasonable flows over the study period.

One other thing to note: Although segment JA5_7480_0001 is a 0001 segment (used to denote an outlet segment), it does have a segment attached downstream -- segment [JA5_7520_0000](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/68372/) [Appomattox River below Brasfield Dam] -- perhaps the 0001 segment is only meant to model the impoundment and not accurately reflect Appomattox River flows?  Note that the downstream 0000 segment is a coastal segment, though.

Rob guesses that an alternative runoff set or some other set is hardwired into the JA5_7480_0001 segment -- something to dig into when he returns.

Dashboards comparing p6 base and climate change scenarios for each of these segments follow:

[Appomattox_0001_Vahydro_Vs_Vahydro_Dashboard_2019.pdf](https://github.com/HARPgroup/cbp6/files/3780061/Appomattox_0001_Vahydro_Vs_Vahydro_Dashboard_2019.pdf)

[JA2_7570_7480_WestCreek_Vahydro_Vs_Vahydro_Dashboard_2019.pdf](https://github.com/HARPgroup/cbp6/files/3780026/JA2_7570_7480_WestCreek_Vahydro_Vs_Vahydro_Dashboard_2019.pdf)

[JA4_7470_7480_Appomattox_Vahydro_Vs_Vahydro_Dashboard_2019.pdf](https://github.com/HARPgroup/cbp6/files/3780028/JA4_7470_7480_Appomattox_Vahydro_Vs_Vahydro_Dashboard_2019.pdf)

**Comment by rburghol** [comment]
Thanks Daniel!

**Comment by rburghol** [comment]
BTW - these results look good, and to note, there has been a pretty substantial change in operations in this reservoir since about 2010, and since this model is run in "scenario" mode, not "historic" mode, the management rule framework uses only the new rules.  If we were running these in "historic" mode, we would make sure that it used the old rules prior to 2010 (or 2011 or something), and then the new rules only in the later years.  Good stuff -- thanks again!
