### ISSUE TITLE
BUG - Varkey overwrite on Properties - SIC Code

### ISSUE THREAD

**Issue by jmineva** [HARPgroup/vahydro#471]
#### Problem
We're in the midst of Hardcopy form edits ( d.alpha/admin/structure/views/view/vwuds_hardcopy_template/edit/page_2) for sending paper Annual Reporting forms via mail. 

Gouri noticed an Organization  (Knicely d.alpha/ows-vwuds-organization-info/481127)  has the measuring point form appearing multiple times (6 times) in their packet when they in fact only have just 1 intake.  I think the issue is because the [SIC Code Property Varkey](http://deq1.bse.vt.edu:81/d.alpha/admin/content/dh_features/manage/481137/dh_properties) is somehow overwriting the several of the Properties that are pulled to show in that view. 

![image](https://user-images.githubusercontent.com/53624761/145393099-64263e75-0f32-4690-b8d6-03e9b58b608b.png)

I came to this conclusion when I exposed the 6 properties that have relationships to no longer be "Exclude from display" so it would show at the top of each form. Sure enough, the SIC Code field has 6 different values meaning it's pulling the propcodes from the other properties instead of just the SIC Code property. 

#### Solution
Once the properties have their correct varkeys, the forms *should* show correctly.

**Comment by rburghol** [comment]
Finding instances of these as:
```
select * from (select featureid, count(*) from dh_properties where propname <> 'sic_code' and varid in (select hydroid from dh_variabledefinition where varkey = 'sic_code') group by featureid) as foo where count > 1;

```

Preview an update:
```
select a.pid, a.varid, a.propname, b.hydroid as new_varid
from dh_properties as a 
left outer join dh_variabledefinition as b 
on (
  a.propname = b.varname
)
where propname not in ( 'SIC Code','sic_code')
and varid in (select hydroid from dh_variabledefinition where varkey = 'sic_code')
;


```

**Comment by jmineva** [comment]
This is great Rob! There should be 5 variables that got the sic_code varkey wrongly set. 
- vpdes_permitno
- vdh_pwsid
- water_act_status
- vadeq_vwuds_mp_subtype
- ows_mp_source_type

Out of curiosity, how many result instances were returned from that first query? And could you include some HydroIDs?

We should make the update on the Alpha data first. I'll check the Knicely intake and some of the other HydroIDs that you send along. After that QA, we can do the update on Live.

**Comment by rburghol** [comment]
Thanks for the list -- and the steps you outlined -- I like the way you're thinking!

Affected MPs:
- alpha: 319 total properties, 72 hydroids.
- dh: 319 total properties, 72 hydroids.

From that I conclude that all the ones that got clobbered happened before we migrated to the new database server, since they are identical counts.  Hydroids:
```
450316,450317,472978,452830,459285,450303,480103,58755,450305,472085,450334,456165,450328,60436,448786,450306,450322,480569,450337,478192,450183,450182,1490,450329,224995,450314,472758,448785,450310,450321,450319,475515,224986,450313,480101,450335,473225,459362,450311,450190,459351,448787,450625,472078,58876,61060,450318,450315,450333,443152,456164,450364,224984,459274,459240,1611,59912,450302,481137,450338,480102,450336,450562,450312,453605,453182,450297,448765,476575,450611,450320,453604
```

**Comment by rburghol** [comment]
Just to follow-up, updates performed on live system.

**Comment by jmineva** [comment]
Fantastic!
