### ISSUE TITLE
Lake Monticello (VWP 19-2043)

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#624]
- Tasks:
  - [x] Verify Model Segments (see **Flow Table** below for details)
    - [x] Verify Beaver Creek
    - [x] Verify Ivy Creek
    - [x] Verify Buck Mtn
    - [x] Verify Mechums
        - Gave greater than 0 runoff for every year through 2020
    - [x] Verify SH
      - XX Currently 0.0 for flows, something is not set up correctly.
    - [x] Verify Mormons
    - [x] Verify NF Rivanna
    - [x] Verify Ragged
    - [x] Verify SF Rivanna
  - [x] New 2020 runoff dataset? (see **Verify New Runoff Dataset** Below)
  - [x] Run model with proposed 10% flowby (see if it'll work)
  - [x] Run mode with current (zero) flow by 
  - [x] Do analysis
    - [x] include runid 200, which shows flat demand at current levels from RWSA, which results in lower point sources and therefore base flows, and is the most scarce scenario.
- Summary: (note: 6001 is updated met because lower Rivanna did not have met in 2019/2020 yet in prior runs)
`rmarkdown::render('C:/usr/local/home/git/vahydro/R/examples/VWP_CIA_Summary.Rmd', output_file = '/WorkSpace/modeling/projects/james_river/rivanna/lake_monticello/lake_monticello_v08.docx', params = list( doc_title = 'Technical Evaluation – VWP 19-2043 Lake Monticello', rseg.hydroid = 68137, fac.hydroid = 72634, runid.list = c("runid_400","runid_6","runid_601"), intake_stats_runid = 400,upstream_rseg_ids=c(68183, 68123, 68309), preferred_runid = "runid_6", cu_model = 337730, cu_pre_var='Qnatural', cu_post_var='Qout'  ))`
- VAHydro links:
  - Lake Monticello model: om-model-info/4728094
  - Beaver Creek (upstream): om-model-info/4431664
  - Mechums River (up): om-model-info/4711088
  - South Fork Rivanna (up): om-model-info/4712170
  - Rivanna River: om-model-info/4713184/dh_properties
  - Sugar Hollow: om-model-info/4712896 (elid: 337718))
  - Moormans: om-model-info/4711272 (elid: 337720)
- Permit request:
  - Has model, has annual and daily max in model that match permit application.
  - Is *not* pump store? Currently has no pump-store function enabled in model.
  - Has no flow-by in old, permit. only condition was to pump at a "constant rate when flow in Rivanna at Palmyra is under 300cfs".
  - Test with flowby 90% in runid 600
- Old Permit info:
  - [Final permit 950176.pdf](https://github.com/HARPgroup/vahydro/files/9121531/Final.permit.950176.pdf)
  - [Fact Sheet 950176.pdf](https://github.com/HARPgroup/vahydro/files/9121534/Fact.Sheet.950176.pdf)

![image](https://user-images.githubusercontent.com/29379385/179241587-16aec3b5-5ffc-4271-94f6-912fc77c0bb6.png)

### Flow Table
|     pid|propname                         |hydrocode                                           | featureid|riverseg                            |   L90_201|   L90_401|  L90_2020|       da|       da|
|-------:|:--------------------------------|:---------------------------------------------------|---------:|:-----------------------------------|---------:|---------:|---------:|--------:|--------:|
| 4709453|Ivy Creek                        |vahydrosw_wshed_JL2_6441_6520_ivy_creek             |     68185|JL2_6441_6520_ivy_creek             |  3.098298|  3.614031|  3.692312|       NA|       NA|
| 5737700|Ragged Mountain                  |vahydrosw_wshed_JL4_6520_6710_ragged_mtn            |     68210|NA                                  |  0.000000|        NA|  0.000000|   1.8000|   1.8000|
| 4431664|Beaver Creek - VAHydro 1.0       |vahydrosw_wshed_JL1_6560_6440_beaver_creek          |     68123|JL1_6560_6440_beaver_creek          |  0.949731|  0.949739|  0.815901|   9.5200|   9.5200|
| 4712896|Sugar Hollow                     |vahydrosw_wshed_JL2_6440_6441_moormans_sugar_hollow |     68308|JL2_6440_6441_moormans_sugar_hollow |  0.000000|  0.000000|  0.000000|  17.0000|  17.0000|
| 5738917|Buck Mountain Creek              |vahydrosw_wshed_JL2_6440_6441_buck_mtn_creek        |     68208|JL2_6440_6441_buck_mtn_creek        |  3.145801|  3.762313|  3.834452|  36.0000|  36.0000|
| 4711272|Moormans River                   |vahydrosw_wshed_JL2_6440_6441                       |     68320|JL2_6440_6441                       |  4.644989|  0.000000|  4.947692|  59.7000|  59.7000|
| 4711088|Mechums River                    |vahydrosw_wshed_JL1_6560_6440                       |     68309|JL1_6560_6440                       | 10.379600| 13.841446| 12.469974|  99.5500|  99.5500|
| 4712752|North Fork Rivanna River         |vahydrosw_wshed_JL2_6240_6520                       |     68301|JL2_6240_6520                       |  6.073993|  0.000000|  4.247870| 176.8600| 176.8600|
| 4712170|South Rivanna River Reservoir    |vahydrosw_wshed_JL2_6441_6520                       |     68183|JL2_6441_6520                       | 12.915171| 23.878841| 14.517804| 259.1000| 259.1000|
| 4713426|Rivanna River @ James Confluence |vahydrosw_wshed_JL4_6710_6740                       |     68300|JL4_6710_6740                       | 68.750452| 73.725319| 78.752108| 769.1791| 769.1791|

### MP Table

|      lat|       lon|label                                  |
|--------:|---------:|:--------------------------------------|
| 38.10222| -78.46889|SOUTH RIVANNA WTP                      |
| 38.05537| -78.71419|OLD TRAIL GOLF CLUB                    |
| 38.00694| -78.70194|MILLER SCHOOL OF ALBEMARLE             |
| 38.06750| -78.66083|CROZET WTP                             |
| 37.94145| -78.33655|LAKE MONTICELLO WTP                    |
| 38.03861| -78.54028|Birdwood Golf Course                   |
| 37.89944| -78.32000|LAKE MONTICELLO GOLF COURSE            |
| 37.98333| -78.26944|Fluvanna Correctional Center for Women |
| 37.97889| -78.38306|GLENMORE COUNTRY CLUB                  |
| 38.05000| -78.45194|MEADOWCREEK GOLF COURSE                |
| 38.00864| -78.35449|KESWICK HALL & GOLF CLUB               |

### Verify new runoff dataset
- Test land segs were imported
  - Yes, but test runs 801 did not yield non-zero runoffs. 
  - However, at least one table was verified: `select extract(year from to_timestamp(timestamp)), avg(for_agwo) from cbp_p6_cfbase30y20180615_vadeq_n51003 group by extract(year from to_timestamp(timestamp)) order by extract(year from to_timestamp(timestamp));`

**Comment by ryugreen** [comment]
Update demands are in gitlab: https://gitlab.deq.virginia.gov/VAHydro/VAHydro/-/issues/114
