### ISSUE TITLE
Drought Map not updating 11/2022

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#731]
Two separate bugs, both which showed up after the mass system update on 11/6/2022
- download of raster data was seemingly broken on deq1
- map rendered incompletely

#### Precip Raster Download
- problem was that after update, the postgis tool `raster2pgsql` had an incompatible library.  
- This may stem from the fact that deq1 was originally ubuntu 18+ and the upgrade in place screwed libraries making them brittle
- solution: do the download and raster insert on deq2, since deq2 was fine, even after the system update, and no amount of trying could get the `raster2pgsql` to be installed with version 12 or 14 of postgresql, an the version 15 of postgresql seems to have a broken postgis/raster2pgsql install
  - fwiw, see [this comment for how to remove and install the raster2pgsql utility](https://github.com/HARPgroup/vahydro/issues/506#issuecomment-1346838577) which does NOT come standard with the basic postgis install any longer.

#### Map rendered incompletely
- Occurred after the Nov 6 upgrade also?
- Can't figure it out:
  - when accessing the file in "mode=map", which ships an image, not an html page, the image is incomplete.
  - when accessing the file without mode=map, it creates a map in the scratch directory that is fully rendered.
- maybe this is related to update problems on deq1, but doesn't matter since it is the only one with mapserver configured, we need to use it.  
- Workaround was use teh normal html download with wget, then use shell scripting to find the newest file and move to `virginia_drought.png` for linking in the state drought page.
 - change: 
   - `wget -O virginia_drought.png "https://localhost/cgi-bin/mapserv?map=/var/www/html/mapserv/vahydro_drought_status-4-metrics-live.map&layers=poli_bounds&layers=proj_seggroups&mode=map&format=image/png" --no-check-certificate`
 - to: 
```
wget -O virginia_drought.png "https://localhost/cgi-bin/mapserv?map=/var/www/html/mapserv/vahydro_drought_status-4-metrics-live.map&layers=poli_bounds&layers=proj_seggroups" --no-check-certificate
newmap=`ls -rt /var/www/html/drought/state/images/maps/ | grep imageMapFile | tail -n 1`
mv /var/www/html/drought/state/images/maps/${newmap} /var/www/html/drought/state/images/maps/virginia_drought.png
```

**Comment by rburghol** [comment]
@jdkleiner - I think I have sorted these out.  See these two commits:
- https://github.com/HARPgroup/vahydro/pull/730
- https://github.com/HARPgroup/vahydro/commit/ed5e4f723b0f3078cb42a4c9cb40878de930de28

**Comment by jdkleiner** [comment]
@rburghol You're the man! Map looks good, I'll monitor over the next couple days to ensure the precip gets updated as expected before closing the issue. Thanks!

**Comment by rburghol** [comment]
My pleasure! The moral of the story… Never update your server :)

**Comment by dentonyoder** [comment]
NO,
Please, that is not the moral...  I think the moral is to always use the
current distribution so that apt upgrade doesn't trash your setup.

Denton Yoder (He/Him)
***@***.***
Computer Systems Engineer
Biological Systems Engineering
Virginia Tech
540.268.0556 Office, Lab
540.230.8302 cell
106 Seitz (IT Lab)

Rose

**Comment by rburghol** [comment]
I was just joking :)

**Comment by rburghol** [comment]
@dentonyoder to describe the systems clearly:
- the deq1 machine and the deq2 machine have both been handled with standard release packages exclusively managed with `apt`
- Deq2 has had zero problems during this update, deq1 has been a perennial problem, with glitches frequently arising post-update. 
- My recollection is that deq1 was upgraded in place from a prior 18.04 install (tho that memory is now vague). 
- Either way, deq2 handled this just fine, and as I noted above, the *fix* to this problem was to move a task from being executed on deq1 to be executed on deq2.

**Comment by jdkleiner** [comment]
@rburghol Hey Rob, looks like the drought cron hasn't run for today, is this related to deq-drought vs. deq-drought-model?
